[project]
name = "streamlit-gantt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plotly>=6.0.1",
    "streamlit>=1.45.0",
]
